/*
 * Project name:
     MyProject.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     5/7/2023
 * Test configuration:
     MCU:             STM32F407VG
     Dev.Board:       EasyMx_PRO_v7_for_STM32_ARM_9A
     Oscillator:      16000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "MyProject_objects.h"

int state;
void main() {

  Start_TP();

  GPIO_Digital_Input(&GPIOC_BASE, _GPIO_PINMASK_0);
  GPIO_Digital_Output(&GPIOD_BASE, _GPIO_PINMASK_ALL);

   state=1;
  while (1) {
    Check_TP();
     if(Button(&GPIOC_IDR, 0,1, 1) )
  {
    if(state==1)
    {
        DrawScreen(&Screen2)  ;
        state=2;
    }
    else if(state==2)
    {   DrawScreen(&Screen1)  ;
        state=1;
    }
    }

  }
}
